[package]
name = "rust_l4n_material_proxy_plugin"
version = "0.2.0"
edition = "2024"
description = "Rust L4N plugin: register custom material proxies (VMT $proxy) to Rust functions with configurable params"

[lib]
name = "rust_l4n_material_proxy_plugin"
crate-type = ["cdylib"]

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
uuid = { version = "1.24.0", features = ["v4"] }
